import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js13 Blog",
  description: "Generated by Next.js13 Blog",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header>Header</header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
