import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Next.js13 Blog",
  description: "Generated by Next.js13 Blog",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-600 text-slate-50">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
